---
title: "assignment_b1"
author: "HaoxiangLei"
date: "2022-10-30"
output: github_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

## Exercise 1: Make a Function
```{r}
library(datateachr)
library(tidyverse)
library(testthat)
library(dplyr)
library(digest)
```

## Exercise 1: Make a Function
```{r}
pick_n_smallest <- function(data, col_label, n){
  data <- arrange(data, {{col_label}})
  stopifnot(is.numeric(n))
  stopifnot(n <= nrow(data))
  result <- data[0:n,]
  list(result)
}
```

## Exercise 2: Document your Function
```{r}
#' Select the n smallest data according to a varible in the table
#' @details the function is aimed to pick up the first n rows of arranged table based on one of the varible in table
#' @param data is the data table we will focus on
#' @param col_label is the varible inside the data we will sort.
#' @param n is the number of the rows we will use
#' @return the new table with n rows

```


## Exercise 3: Include examples
```{r}
# for example: we would like get the first 100 rows of the data sorted BY radius_mean
pick_n_smallest(cancer_sample, col_label = radius_mean, 100)
```

```{r}
# Since the n is bigger than the number of rows
pick_n_smallest(cancer_sample, col_label = texture_mean, 1500000)
```
## Exercise 4: Test
```{r}
# it checked whether the head of two table are the same
cancer_check <- arrange(cancer_sample, area_mean)
test_that("output the first n rows", {
    expect_equal(head(pick_n_smallest(cancer_sample, col_label = area_mean, 10)[[1]]), head(cancer_check[0:10,]))
})
```

```{r}
# it checked the length of the two table
cancer_check <- arrange(cancer_sample, area_mean)
test_that("output the first n rows", {
    expect_equal(nrow(pick_n(cancer_sample,col_label = area_mean, 20)[[1]]), 20)
})
```
```{r}
# it checked the function by checking the length of the two table

test_that("output the first n rows", {
    expect_equal(nrow(pick_n(cancer_sample,col_label = area_mean, 100)[[1]]), 100)
})
```

